-- Migration: Drop order_items table
-- Generated by TelemetryFlow RESTful API Generator
-- Copyright (c) 2024-2026 Telemetri Data Indonesia. All rights reserved.

-- Drop trigger
DROP TRIGGER IF EXISTS update_order_items_updated_at ON order_items;

-- Drop indexes
DROP INDEX IF EXISTS idx_order_items_created_at;
DROP INDEX IF EXISTS idx_order_items_order_id;
DROP INDEX IF EXISTS idx_order_items_product_id;
DROP INDEX IF EXISTS idx_order_items_deleted_at;


-- Drop table
DROP TABLE IF EXISTS order_items;